services:
  nextjs-app:
    container_name: ajeromi_container
    image: ajeromi-ifelodun/ajeromi_website:latest  
    build: .
    env_file:
      - .env  
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production  
    volumes:
      - /app/node_modules  